# Site settings
title: Duygu Dağdelen
description: A super cool website built with Jekyll
url: "https://dduyg.github.io" # Your site's URL
baseurl: "/GlitchyGarden" # Set this if your site is hosted in a subdirectory, e.g., "/blog"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-gist # Plugin that allows you to embed GitHub Gists directly
  - jekyll-seo-tag # Plugin to generate SEO meta tags

# SEO settings
seo:
  name: Your Awesome Website
  title: Your Awesome Website
  description: A super cool website built with Jekyll
  keywords: jekyll, github-pages, website, awesome
  social:
    twitter: "@yourtwitterhandle"
    facebook: "yourfacebookpage"
    instagram: "yourinstagramhandle"

# Socials
networks:
  - title: GitHub
    url: https://github.com/yourusername
    icon: github
  - title: Instagram
    url: https://instagram.com/yourusername
    icon: instagram
  - title: Medium
    url: https://medium.com/@yourusername
    icon: medium
