# Site settings
title: Duygu Dağdelen
author: Duygu Dağdelen
description: As a data scientist with a flair for creativity, bringing ideas to life by developing data products
url: "https://dduyg.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-gist # Plugin that allows you to embed GitHub Gists directly
  - jekyll-seo-tag # Plugin to generate SEO meta tags

# SEO settings
seo:
  name: Your Awesome Website
  title: Your Awesome Website
  description: A super cool website built with Jekyll
  keywords: jekyll, github-pages, website, awesome
  social:
    twitter: "@yourtwitterhandle"
    facebook: "yourfacebookpage"
    instagram: "yourinstagramhandle"

# Socials
networks:
  - title: GitHub
    url: https://github.com/dduyg
    icon: github
  - title: Instagram
    url: https://instagram.com/insert.data
    icon: instagram
  - title: Ko-fi
    url: https://ko-fi.com/dduyg
    icon: heart outline
  - title: Medium
    url: https://medium.com/@dduyg
    icon: medium m
  - title: Behance
    url: https://www.behance.net/dduyg
    icon: behance square

prints: https://www.inprnt.com/gallery/insert.data
email: dduyg.contact@gmail.com
     
